[package]
name = "OxyBoot"
description="A custom bootloader for my future OxyOS project"
version = "0.1.0"
edition = "2024"
license="MIT"
#documentation = "" TODO!
keywords=["bootloader"]
authors = [
    "LittleHobbitFrodo <https://github.com/LittleHobbitFrodo>"
]

[profile.release]
opt-level = 3
panic="abort"

[dependencies]
allocator-api2 = "0.3.0"
bitflags = "2.9.1"
serde = { version = "1.0.219", features = ["derive"] }
spin = "0.10.0"
toml = "0.9.2"
uefi = { version="=0.35.0", default-features = false, features = []}
oxyboot_requests={ path="oxyboot_requests", features = ["bootloader"], version="1.0.0"}
#elf_loader = { version = "0.12.0", default-features = false, features = ["rel", "version", "portable-atomic"]}
goblin = "0.10.3"
x86_64 = { version="0.15.4", features = ["instructions"], default-features = false}
