#!/bin/bash

#   script for build aoutomation (+ run)

args="${@:1}"

for i in $args; do

  echo i: $i

  case "$i" in
    build)

      echo building OxyBoot

      cargo build --target x86_64-unknown-uefi --release

      if [ "$?" != 0 ]; then
        echo ERROR: failed to build the bootloader
        exit 1
      fi

      if [ ! -e ./efi-img/EFI/BOOT ]; then
          mkdir -p efi-img/EFI/BOOT/
      fi

      cp ./target/x86_64-unknown-uefi/release/OxyBoot.efi ./efi-img/EFI/BOOT/BOOTX64.EFI

    ;;
    run)

      qemu-system-x86_64 \
  -drive format=raw,file=fat:rw:efi-img/ \
  -bios /usr/share/OVMF/OVMF_CODE.fd

    ;;

  esac

done
