#!/bin/bash

#   script for build aoutomation (+ run)

args="${@:1}"

for i in $args; do

	case "$i" in
		build)
			#	bootloader compilation

		echo building OxyBoot

		cargo build --target x86_64-unknown-uefi --release

		if [ "$?" != 0 ]; then
			echo ERROR: failed to build the bootloader
			exit 1
		fi

		#	creating the UEFI syspart structure

		if [ ! -e ./efi-img/EFI/BOOT ]; then
			mkdir -p efi-img/EFI/BOOT/
		fi

		cp ./target/x86_64-unknown-uefi/release/OxyBoot.efi ./efi-img/EFI/BOOT/BOOTX64.EFI

		#	add bootloader configuration
		#mkdir -p efi-img/oxy/
		#cp ./oxyboot.toml ./efi-img/oxy/

		#	copy kernel executable
		cp ./kernel/kernel.elf ./efi-img/oxy/kernel.elf


	;;
	build-kernel)
		#	compile the kernel
		cd ./kernel/
		./build.sh

		if [ "$?" != 0 ]; then
			echo "failed to compile example kernel"
			exit 1
		fi
		cd ..
	;;
	run)

		qemu-system-x86_64 \
		-drive format=raw,file=fat:rw:efi-img/ \
		-bios /usr/share/OVMF/OVMF_CODE.fd
  		# -d int,cpu_reset,guest_errors \	#	event logs
  		# -D qemu.log

	;;
esac

done
