#!/bin/bash

#   script for build aoutomation (+ run)

args="${@:1}"

for i in $args; do

	case "$i" in
		build)

		echo building OxyBoot

		cargo build --target x86_64-unknown-uefi --release

		if [ "$?" != 0 ]; then
			echo ERROR: failed to build the bootloader
			exit 1
		fi

		if [ ! -e ./efi-img/EFI/BOOT ]; then
			mkdir -p efi-img/EFI/BOOT/
		fi

		cp ./target/x86_64-unknown-uefi/release/OxyBoot.efi ./efi-img/EFI/BOOT/BOOTX64.EFI

		#	add bootloader configuration
		mkdir -p efi-img/oxy/
		cp ./oxyboot.toml ./efi-img/oxy/

		#	copy kernel executable

		cp ./kernel.elf ./efi-img/oxy/kernel.elf


	;;
	run)

		qemu-system-x86_64 \
		-drive format=raw,file=fat:rw:efi-img/ \
		-bios /usr/share/OVMF/OVMF_CODE.fd

	;;
esac

done
